# Generated by Django 5.2.14 on 2026-07-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherreport',
            name='content',
            field=models.TextField(blank=True, verbose_name='Contenido'),
        ),
    ]
