# Generated by Django 5.2.14 on 2026-07-23 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_weatherreport_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='earlywarning',
            options={'default_permissions': (), 'ordering': ['-date'], 'permissions': (('view_early_warning', 'Ver'), ('add_early_warning', 'Añadir'), ('change_early_warning', 'Editar'), ('delete_early_warning', 'Eliminar')), 'verbose_name': 'Aviso de Alerta Temprana', 'verbose_name_plural': 'Avisos de Alertas Tempranas'},
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'default_permissions': (), 'ordering': ['invoice', 'codigo'], 'permissions': (('view_invoice_item', 'Ver'), ('add_invoice_item', 'Añadir'), ('change_invoice_item', 'Editar'), ('delete_invoice_item', 'Eliminar')), 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='stormwarning',
            options={'default_permissions': (), 'ordering': ['-date'], 'permissions': (('view_storm_warning', 'Ver'), ('add_storm_warning', 'Añadir'), ('change_storm_warning', 'Editar'), ('delete_storm_warning', 'Eliminar')), 'verbose_name': 'Aviso de Tormenta', 'verbose_name_plural': 'Avisos de Tormentas'},
        ),
        migrations.AlterModelOptions(
            name='tropicalcyclone',
            options={'default_permissions': (), 'ordering': ['-date'], 'permissions': (('view_tropical_cyclone', 'Ver'), ('add_tropical_cyclone', 'Añadir'), ('change_tropical_cyclone', 'Editar'), ('delete_tropical_cyclone', 'Eliminar')), 'verbose_name': 'Aviso de Ciclón Tropical', 'verbose_name_plural': 'Avisos de Ciclones Tropicales'},
        ),
        migrations.AlterModelOptions(
            name='weatherreport',
            options={'default_permissions': (), 'ordering': ['-date'], 'permissions': (('view_weather_report', 'Ver reportes meteorológicos'), ('view_weather_today', 'Ver Tiempo Hoy'), ('add_weather_today', 'Añadir Tiempo Hoy'), ('change_weather_today', 'Editar Tiempo Hoy'), ('delete_weather_today', 'Eliminar Tiempo Hoy'), ('view_weather_tomorrow', 'Ver Tiempo Mañana'), ('add_weather_tomorrow', 'Añadir Tiempo Mañana'), ('change_weather_tomorrow', 'Editar Tiempo Mañana'), ('delete_weather_tomorrow', 'Eliminar Tiempo Mañana'), ('view_weather_commentary', 'Ver Comentario del Tiempo'), ('add_weather_commentary', 'Añadir Comentario del Tiempo'), ('change_weather_commentary', 'Editar Comentario del Tiempo'), ('delete_weather_commentary', 'Eliminar Comentario del Tiempo'), ('view_weather_note', 'Ver Nota Meteorológica'), ('add_weather_note', 'Añadir Nota Meteorológica'), ('change_weather_note', 'Editar Nota Meteorológica'), ('delete_weather_note', 'Eliminar Nota Meteorológica')), 'verbose_name': 'Reporte Meteorológico', 'verbose_name_plural': 'Reportes Meteorológicos'},
        ),
        migrations.AlterField(
            model_name='earlywarning',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_warnings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='dashboard.servicesubscription'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stormwarning',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_warnings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tropicalcyclone',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_warnings', to=settings.AUTH_USER_MODEL),
        ),
    ]
