# Generated by Django 5.2.14 on 2026-07-22 17:28

import apps.common.utils
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'verbose_name': 'Perfil Grupo',
                'verbose_name_plural': 'Perfiles Grupos',
                'permissions': (('view_group', 'Ver'), ('add_group', 'Añadir'), ('change_group', 'Editar'), ('delete_group', 'Eliminar')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apps.common.utils.image_upload_path)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_ldap', models.BooleanField(default=False)),
                ('newsletter', models.BooleanField(default=False, verbose_name='Recibe novedades por correo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'permissions': (('view_profile', 'Ver'), ('add_profile', 'Añadir'), ('change_profile', 'Editar'), ('delete_profile', 'Eliminar')),
                'default_permissions': (),
            },
        ),
    ]
