repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
        exclude: '^static/'
      - id: end-of-file-fixer
        exclude: '^static/'
      - id: trailing-whitespace
        exclude: '^static/'

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: "static/|staticfiles/|\\.secrets\\.baseline$|.*\\.min\\.js$|.*\\.map$"

  - repo: https://github.com/djlint/djlint
    rev: v1.46.2
    hooks:
      - id: djlint-django
      - id: djlint-reformat-django
