repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.1
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-secrets
        exclude: "static/|staticfiles/|.*\\.min\\.js$|.*\\.map$"

  - repo: https://github.com/djlint/djlint
    rev: v1.44.0
    hooks:
      - id: djlint-lint
      - id: djlint-reformat
