# Generated by Django 5.2.14 on 2026-07-22 17:28

import apps.common.utils
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('institution', models.CharField(blank=True, max_length=200, verbose_name='Institución')),
                ('orcid_id', models.CharField(blank=True, max_length=19, verbose_name='ID ORCID')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['last_name', 'first_name'],
                'permissions': (('view_author', 'Ver'), ('add_author', 'Añadir'), ('change_author', 'Editar'), ('delete_author', 'Eliminar')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ScientificPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('publication_date', models.DateField(verbose_name='Fecha de Publicación')),
                ('summary', models.TextField(verbose_name='Resumen')),
                ('pdf_file', models.FileField(upload_to=apps.common.utils.pdf_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Archivo PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_publications', to='publications.author', verbose_name='Autor')),
                ('coauthors', models.ManyToManyField(blank=True, related_name='coauthored_publications', to='publications.author', verbose_name='Coautores')),
            ],
            options={
                'verbose_name': 'Publicación Científica',
                'verbose_name_plural': 'Publicaciones Científicas',
                'ordering': ['-publication_date'],
                'permissions': (('view_scientific_publication', 'Ver'), ('add_scientific_publication', 'Añadir'), ('change_scientific_publication', 'Editar'), ('delete_scientific_publication', 'Eliminar')),
                'default_permissions': (),
            },
        ),
    ]
