# Generated by Django 5.2.14 on 2026-07-27 17:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la empresa')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('codigo_reeup', models.CharField(max_length=50, verbose_name='Código REEUP')),
                ('nit', models.CharField(max_length=50, verbose_name='NIT')),
                ('cuenta_bancaria', models.CharField(max_length=50, verbose_name='Cuenta bancaria')),
                ('agencia_bancaria', models.CharField(max_length=100, verbose_name='Agencia bancaria')),
                ('telefonos', models.CharField(max_length=100, verbose_name='Teléfonos')),
                ('registro_comercial', models.CharField(help_text='Ej: A09404', max_length=50, verbose_name='Registro Comercial')),
            ],
            options={
                'verbose_name': 'Datos de la empresa',
                'verbose_name_plural': 'Datos de la empresa',
                'permissions': [('view_companysettings', 'Ver'), ('change_companysettings', 'Editar')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='EmailRecipientList',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Lista de correo',
                'verbose_name_plural': 'Listas de correo',
                'permissions': [('view_emailrecipientlist', 'Ver'), ('add_emailrecipientlist', 'Añadir'), ('change_emailrecipientlist', 'Editar'), ('delete_emailrecipientlist', 'Eliminar')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('maintenance_mode', models.BooleanField(default=True, verbose_name='Modo mantenimiento')),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuración del sitio',
                'permissions': [('view_siteconfiguration', 'Ver'), ('change_siteconfiguration', 'Editar')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='EmailRecipient',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('recipient_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='core.emailrecipientlist', verbose_name='Lista de correo')),
            ],
            options={
                'verbose_name': 'Correo',
                'verbose_name_plural': 'Correos',
                'permissions': [('view_emailrecipient', 'Ver'), ('add_emailrecipient', 'Añadir'), ('change_emailrecipient', 'Editar'), ('delete_emailrecipient', 'Eliminar')],
                'default_permissions': (),
            },
        ),
    ]
