"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
import sys
from pathlib import Path
from dotenv import load_dotenv
from str2bool import str2bool
from django.core.management.utils import get_random_secret_key
from django.contrib.messages import constants as messages

# Load environment variables
load_dotenv()

# =====================
# CORE CONFIGURATION
# =====================

BASE_DIR = Path(__file__).resolve().parent.parent
DEBUG = str2bool(os.getenv('DEBUG', 'False'))

# Validación crítica de DEBUG vs ALLOWED_HOSTS
if DEBUG and 'localhost' not in os.environ.get('ALLOWED_HOSTS', ''):
    raise RuntimeError("DEBUG=True pero 'localhost' no está en ALLOWED_HOSTS. Esto no es seguro.")

# =====================
# SECURITY SETTINGS
# =====================

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# Auto-generación segura de claves
if not SECRET_KEY:
    if os.getenv('PRODUCTION'):  # Entorno de producción
        SECRET_KEY = get_random_secret_key()
        print(f"⚠️ SECRET_KEY generada automáticamente para producción")
    elif 'runserver' in sys.argv:  # Desarrollo local
        SECRET_KEY = 'django-insecure-dev-key' + get_random_secret_key()[:32]
        print("⚠️ Usando clave temporal para desarrollo. Configurar SECRET_KEY en producción.")

# Bloqueo estricto en producción
if not DEBUG and SECRET_KEY.startswith('django-insecure-'):
    raise ValueError("¡Clave insegura detectada en producción!")

# Security: Recommended for production
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
# =====================
# HOST CONFIGURATION
# =====================

# Hosts and CSRF Configurations
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',')
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',')
        
# External hostname configuration
if EXTERNAL_HOSTNAME := os.getenv('EXTERNAL_HOSTNAME'):
    ALLOWED_HOSTS.append(EXTERNAL_HOSTNAME)
    if not any(EXTERNAL_HOSTNAME in origin for origin in CSRF_TRUSTED_ORIGINS):
        CSRF_TRUSTED_ORIGINS.append(f'https://{EXTERNAL_HOSTNAME}')

# =====================
# APPLICATION DEFINITION
# =====================

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

EXTERNAL_APPS = [
    'drf_redesign',
    'rest_framework',
    'drf_spectacular',
    'drf_spectacular_sidecar', # for static schema generation
]

MY_APPS = [
    'api',
    'home',
    'login',
    'accounts',
    'dashboard',
]

INSTALLED_APPS = DJANGO_APPS + EXTERNAL_APPS + MY_APPS

# =====================
# MIDDLEWARE
# =====================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.check_user_profile.CheckUserProfileMiddleware',
    'dashboard.middleware.maintenance_mode.MaintenanceModeMiddleware',  # Middleware de mantenimiento
]

# =====================
# ROOT URL
# =====================

ROOT_URLCONF = 'core.urls'

# =====================
# TEMPLATES
# =====================

HOME_TEMPLATES = os.path.join(BASE_DIR, 'templates')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [HOME_TEMPLATES],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'dashboard.context_processors.notification_counts',
            ],
        },
    },
]

# =====================
# WSGI APPLICATION
# =====================

WSGI_APPLICATION = 'core.wsgi.application'

# =====================
# DATABASE
# =====================

DB_ENGINE = os.getenv('DB_ENGINE', None)
DB_USERNAME = os.getenv('DB_USERNAME', None)
DB_PASS = os.getenv('DB_PASS', None)
DB_HOST = os.getenv('DB_HOST', None)
DB_PORT = os.getenv('DB_PORT', None)
DB_NAME = os.getenv('DB_NAME', None)

if DB_ENGINE and DB_NAME and DB_USERNAME:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.' + DB_ENGINE,
            'NAME': DB_NAME,
            'USER': DB_USERNAME,
            'PASSWORD': DB_PASS,
            'HOST': DB_HOST,
            'PORT': DB_PORT,
        },
    }
else:
    print("Advertencia: Usando SQLite como base de datos predeterminada.")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }

# =====================
# PASSWORD VALIDATORS
# =====================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# =====================
# LOCALIZATION
# =====================

LANGUAGE_CODE = 'es-mx'
TIME_ZONE = 'America/Havana'
USE_I18N = True
USE_TZ = True

# =====================
# STATIC | MEDIA
# =====================

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
    
# =====================
# X_FRAME_OPTIONS
# =====================

X_FRAME_OPTIONS = 'SAMEORIGIN'  

# =====================
# LOGIN | LOGOUT
# =====================

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'
LOGIN_URL = '/login/'

# =====================
# MESSAGES
# =====================

MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

# =====================
# DEFAULT PK
# =====================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =====================
# REST FRAMEWORK
# =====================

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'DFM12 REST APIs',
    'DESCRIPTION': 'Documentación de la API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_DIST': 'SIDECAR',
    'SWAGGER_UI_FAVICON_HREF': 'SIDECAR',
    'REDOC_DIST': 'SIDECAR',
}

# =====================
# EMAIL CONFIGURATION
# =====================

EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', default=True)
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = os.getenv('EMAIL_PORT')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')

# Lógica de backends (prioridad: Consola > Personalizado > SMTP estándar)
if 'EMAIL_BACKEND' in os.environ:  # Opción 1: Backend explícito (ej: consola)
    EMAIL_BACKEND = os.environ['EMAIL_BACKEND']
elif 'CUSTOM_EMAIL_BACKEND' in os.environ:  # Opción 2: Backend personalizado
    EMAIL_BACKEND = os.environ['CUSTOM_EMAIL_BACKEND']
    EMAIL_USE_SSL = False
# Opción 3: Por defecto Django usará SMTP (no necesitas declararlo)

# =====================
# VALIDATION FINAL
# =====================

required_settings = ['SECRET_KEY', 'ALLOWED_HOSTS', 'EMAIL_HOST']
for setting in required_settings:
    if not globals().get(setting):
        raise ValueError(f"La configuración requerida {setting} no se ha definido correctamente.")