# Generated by Django 5.2.14 on 2026-07-27 17:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.group')),
            ],
            options={
                'verbose_name': 'Perfil de grupo',
                'verbose_name_plural': 'Perfiles de grupos',
                'permissions': [('view_groupprofile', 'Ver perfiles de grupo'), ('add_groupprofile', 'Añadir perfiles de grupo'), ('change_groupprofile', 'Cambiar perfiles de grupo'), ('delete_groupprofile', 'Eliminar perfiles de grupo')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('is_ldap', models.BooleanField(default=False, verbose_name='Usuario LDAP')),
                ('newsletter', models.BooleanField(default=False, verbose_name='Recibir boletín')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'permissions': [('view_profile', 'Ver perfiles'), ('add_profile', 'Añadir perfiles'), ('change_profile', 'Cambiar perfiles'), ('delete_profile', 'Eliminar perfiles')],
                'default_permissions': (),
            },
        ),
    ]
