# Generated by Django 5.2.14 on 2026-07-27 19:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionProfile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission', verbose_name='Permisos')),
            ],
            options={
                'verbose_name': 'Perfil de permisos',
                'verbose_name_plural': 'Perfiles de permisos',
                'ordering': ['name'],
                'permissions': [('view_permissionprofile', 'Ver'), ('add_permissionprofile', 'Añadir'), ('change_permissionprofile', 'Editar'), ('delete_permissionprofile', 'Eliminar')],
                'default_permissions': (),
            },
        ),
    ]
