# Generated by Django 5.2.14 on 2026-07-27 17:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_active', models.BooleanField(default=True, verbose_name='Registro activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado en')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('client_type', models.CharField(choices=[('natural', 'Persona Natural'), ('juridica', 'Persona Jurídica')], default='juridica', max_length=8, verbose_name='Tipo de Cliente')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la Empresa')),
                ('reeup', models.CharField(blank=True, max_length=12, null=True, verbose_name='REEUP')),
                ('nit', models.CharField(blank=True, max_length=11, null=True, verbose_name='NIT')),
                ('account', models.CharField(max_length=16, verbose_name='Cuenta Bancaria')),
                ('agency_bank', models.CharField(blank=True, max_length=100, null=True, verbose_name='Agencia Bancaria')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('phone', models.CharField(max_length=8, verbose_name='Número de Teléfono')),
                ('accept_terms', models.BooleanField(default=False, verbose_name='Aceptó Términos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_customer', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'permissions': (('view_customer', 'Ver'), ('add_customer', 'Añadir'), ('change_customer', 'Editar'), ('delete_customer', 'Eliminar')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_active', models.BooleanField(default=True, verbose_name='Registro activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado en')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Número de factura')),
                ('issue_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de emisión')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='invoices/pdfs/', verbose_name='Archivo PDF')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='¿Anulada?')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Correo enviado')),
                ('email_error', models.TextField(blank=True, null=True, verbose_name='Error al enviar')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='commercial.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-issue_date'],
                'permissions': (('view_invoice', 'Ver'), ('add_invoice', 'Añadir'), ('change_invoice', 'Editar'), ('delete_invoice', 'Eliminar')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_active', models.BooleanField(default=True, verbose_name='Registro activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado en')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('summary', models.CharField(max_length=500, verbose_name='Resumen')),
                ('service_type', models.CharField(choices=[('public', 'Público'), ('commercial', 'Comercial')], default='public', max_length=10, verbose_name='Tipo de Servicio')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='services/pdfs/', verbose_name='Archivo PDF')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/images/', verbose_name='Imagen')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código del servicio')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (CUP)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_created_services', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'permissions': (('view_service', 'Ver'), ('add_service', 'Añadir'), ('change_service', 'Editar'), ('delete_service', 'Eliminar')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ServiceSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_active', models.BooleanField(default=True, verbose_name='Registro activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado en')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de expiración')),
                ('payment_status', models.CharField(choices=[('requested', 'Solicitado'), ('pending', 'Pendiente de pago'), ('paid', 'Pagado'), ('expired', 'Expirado')], default='requested', max_length=20, verbose_name='Estado de pago')),
                ('payment_method', models.CharField(blank=True, choices=[('qr', 'Pago por Código QR'), ('transfer', 'Transferencia Bancaria'), ('presencial', 'Pago Presencial')], max_length=20, null=True, verbose_name='Método de pago')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.customer', verbose_name='Cliente')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.service', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Suscripción de servicio',
                'verbose_name_plural': 'Suscripciones de servicios',
                'permissions': (('view_subscription', 'Ver'), ('add_subscription', 'Añadir'), ('change_subscription', 'Editar'), ('delete_subscription', 'Eliminar')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('codigo', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.TextField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_medida', models.CharField(default='U', max_length=5)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commercial.invoice')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='commercial.servicesubscription')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['invoice', 'codigo'],
                'permissions': (('view_invoice_item', 'Ver'), ('add_invoice_item', 'Añadir'), ('change_invoice_item', 'Editar'), ('delete_invoice_item', 'Eliminar')),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='commercial.servicesubscription', verbose_name='Suscripción'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_active', models.BooleanField(default=True, verbose_name='Registro activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado en')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('number', models.CharField(max_length=50, verbose_name='Número de contrato')),
                ('date', models.DateField(verbose_name='Fecha del contrato')),
                ('commercial_registry', models.CharField(max_length=50, verbose_name='Registro Comercial')),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='commercial.servicesubscription', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ('-date',),
                'permissions': (('view_contract', 'Ver'), ('add_contract', 'Añadir'), ('change_contract', 'Editar'), ('delete_contract', 'Eliminar')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_active', models.BooleanField(default=True, verbose_name='Registro activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado en')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('issued_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de emisión')),
                ('pdf', models.FileField(upload_to='certificates/pdfs/', verbose_name='Certificado PDF')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='commercial.servicesubscription', verbose_name='Suscripción')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['-issued_date'],
                'permissions': (('view_certificate', 'Ver'), ('add_certificate', 'Añadir'), ('change_certificate', 'Editar'), ('delete_certificate', 'Eliminar')),
                'default_permissions': (),
            },
        ),
    ]
