# Generated by Django 5.2.14 on 2026-07-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account',
            field=models.CharField(max_length=16, unique=True, verbose_name='Cuenta Bancaria'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nit',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='NIT'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='reeup',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='REEUP'),
        ),
    ]
