# Generated by Django 5.2.14 on 2026-07-27 19:32

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0002_alter_customer_account_alter_customer_nit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='pdf',
            field=models.FileField(upload_to=apps.core.models.pdf_upload_path, verbose_name='Certificado PDF'),
        ),
    ]
