# Generated by Django 5.2.17 on 2026-10-03 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0005_alter_servicesubscription_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesubscription',
            name='end_date',
        ),
    ]
