# Generated by Django 5.2.14 on 2026-07-27 17:23

import apps.core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecasts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='Fecha')),
                ('lp', models.CharField(choices=[('Luna Nueva', 'Luna Nueva'), ('Creciente', 'Creciente'), ('Cuarto Creciente', 'Cuarto Creciente'), ('Gibosa Creciente', 'Gibosa Creciente'), ('Luna Llena', 'Luna Llena'), ('Gibosa Menguante', 'Gibosa Menguante'), ('Cuarto Menguante', 'Cuarto Menguante'), ('Menguante', 'Menguante')], max_length=20, verbose_name='Fase Lunar')),
                ('nlp', models.CharField(choices=[('Luna Nueva', 'Luna Nueva'), ('Creciente', 'Creciente'), ('Cuarto Creciente', 'Cuarto Creciente'), ('Gibosa Creciente', 'Gibosa Creciente'), ('Luna Llena', 'Luna Llena'), ('Gibosa Menguante', 'Gibosa Menguante'), ('Cuarto Menguante', 'Cuarto Menguante'), ('Menguante', 'Menguante')], max_length=20, verbose_name='Próxima Fase Lunar')),
                ('nlpd', models.DateField(verbose_name='Fecha Próxima Fase')),
                ('sunrise', models.TimeField(verbose_name='Salida Sol')),
                ('sunset', models.TimeField(verbose_name='Puesta Sol')),
                ('uv_index', models.IntegerField(verbose_name='Índice UV')),
            ],
            options={
                'verbose_name': 'Pronóstico',
                'verbose_name_plural': 'Pronósticos',
                'ordering': ('-date',),
                'permissions': (('view_forecast', 'Ver'), ('add_forecast', 'Añadir'), ('change_forecast', 'Editar'), ('delete_forecast', 'Eliminar')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('warning_type', models.CharField(choices=[('early', 'Alerta Temprana'), ('storm', 'Tormenta'), ('tropical_cyclone', 'Ciclón Tropical')], max_length=20, verbose_name='Tipo de aviso')),
                ('summary', models.TextField(verbose_name='Resumen')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.core.models.pdf_upload_path, verbose_name='Archivo PDF')),
                ('valid_until', models.DateTimeField(verbose_name='Válido hasta')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('email_recipient_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.emailrecipientlist', verbose_name='Lista de correos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
                'ordering': ['-date'],
                'permissions': (('view_warning', 'Ver avisos'), ('add_warning', 'Añadir avisos'), ('change_warning', 'Editar avisos'), ('delete_warning', 'Eliminar avisos')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='WeatherReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('summary', models.TextField(max_length=300, verbose_name='Resumen')),
                ('content', models.TextField(blank=True, verbose_name='Contenido')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.core.models.pdf_upload_path, verbose_name='Archivo PDF')),
                ('report_type', models.CharField(choices=[('today', 'Hoy'), ('tomorrow', 'Mañana'), ('commentary', 'Comentario'), ('note', 'Nota')], max_length=20, verbose_name='Tipo')),
                ('email_recipient_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.emailrecipientlist', verbose_name='Lista de Correos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meteo_weather_reports', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Reporte Meteorológico',
                'verbose_name_plural': 'Reportes Meteorológicos',
                'ordering': ['-date'],
                'permissions': (('view_weather_report', 'Ver reportes meteorológicos'), ('view_weather_today', 'Ver Tiempo Hoy'), ('add_weather_today', 'Añadir Tiempo Hoy'), ('change_weather_today', 'Editar Tiempo Hoy'), ('delete_weather_today', 'Eliminar Tiempo Hoy'), ('view_weather_tomorrow', 'Ver Tiempo Mañana'), ('add_weather_tomorrow', 'Añadir Tiempo Mañana'), ('change_weather_tomorrow', 'Editar Tiempo Mañana'), ('delete_weather_tomorrow', 'Eliminar Tiempo Mañana'), ('view_weather_commentary', 'Ver Comentario del Tiempo'), ('add_weather_commentary', 'Añadir Comentario del Tiempo'), ('change_weather_commentary', 'Editar Comentario del Tiempo'), ('delete_weather_commentary', 'Eliminar Comentario del Tiempo'), ('view_weather_note', 'Ver Nota Meteorológica'), ('add_weather_note', 'Añadir Nota Meteorológica'), ('change_weather_note', 'Editar Nota Meteorológica'), ('delete_weather_note', 'Eliminar Nota Meteorológica')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ForecastRegions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('north', 'Costa Norte'), ('interior', 'Interior'), ('south', 'Costa Sur')], max_length=10)),
                ('period', models.CharField(choices=[('morning', 'Mañana'), ('afternoon', 'Tarde'), ('night', 'Noche')], max_length=10)),
                ('period_order', models.IntegerField(default=0, editable=False)),
                ('temp', models.IntegerField(verbose_name='Temperatura')),
                ('weather', models.CharField(choices=[('PN', 'PN'), ('PARCN', 'PARCN'), ('N', 'N'), ('AIS CHUB', 'AIS CHUB'), ('ALG CHUB', 'ALG CHUB'), ('NUM CHUB', 'NUM CHUB'), ('ALG TORM', 'ALG TORM'), ('NUM TORM', 'NUM TORM')], max_length=10, verbose_name='Tiempo')),
                ('wind_dir', models.CharField(choices=[('VRB', 'VRB'), ('N', 'N'), ('NNE', 'NNE'), ('NE', 'NE'), ('ENE', 'ENE'), ('E', 'E'), ('ESE', 'ESE'), ('SE', 'SE'), ('SSE', 'SSE'), ('S', 'S'), ('SSW', 'SSW'), ('SW', 'SW'), ('WSW', 'WSW'), ('W', 'W'), ('WNW', 'WNW'), ('NW', 'NW'), ('NNW', 'NNW')], max_length=10, verbose_name='Dirección del Viento')),
                ('wind_speed', models.CharField(max_length=5, verbose_name='Velocidad del Viento')),
                ('sea_note', models.CharField(blank=True, choices=[('TQ', 'TQ'), ('PO', 'PO'), ('O', 'O'), ('MRJ', 'MRJ'), ('FMRJ', 'FMRJ')], max_length=10, null=True, verbose_name='Mar')),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='meteo.forecasts')),
            ],
            options={
                'verbose_name': 'Pronóstico por Región',
                'verbose_name_plural': 'Pronósticos por Región',
                'ordering': ['forecast', 'region', 'period_order'],
                'permissions': (('view_forecastregions', 'Ver'), ('add_forecastregions', 'Añadir'), ('change_forecastregions', 'Editar'), ('delete_forecastregions', 'Eliminar')),
                'default_permissions': (),
                'unique_together': {('forecast', 'region', 'period')},
            },
        ),
        migrations.CreateModel(
            name='ForecastExtendedDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(verbose_name='Día')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('min_temp', models.IntegerField(verbose_name='Temperatura Mínima')),
                ('max_temp', models.IntegerField(verbose_name='Temperatura Máxima')),
                ('weather', models.CharField(choices=[('PN', 'PN'), ('PARCN', 'PARCN'), ('N', 'N'), ('AIS CHUB', 'AIS CHUB'), ('ALG CHUB', 'ALG CHUB'), ('NUM CHUB', 'NUM CHUB'), ('ALG TORM', 'ALG TORM'), ('NUM TORM', 'NUM TORM')], max_length=10, verbose_name='Tiempo')),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extended_days', to='meteo.forecasts')),
            ],
            options={
                'verbose_name': 'Día Extendido',
                'verbose_name_plural': 'Días Extendidos',
                'ordering': ['forecast', 'day_number'],
                'permissions': (('view_forecastextendedday', 'Ver'), ('add_forecastextendedday', 'Añadir'), ('change_forecastextendedday', 'Editar'), ('delete_forecastextendedday', 'Eliminar')),
                'default_permissions': (),
                'unique_together': {('forecast', 'day_number')},
            },
        ),
    ]
