# Generated by Django 5.2.14 on 2026-07-27 17:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=15, verbose_name='Nombre')),
                ('code', models.CharField(help_text='Código numérico de 2 dígitos (ej: 09)', max_length=2, unique=True, validators=[django.core.validators.RegexValidator('^\\d{2}$', 'El código debe ser numérico de 2 dígitos (ej: 09).')], verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'ordering': ('name',),
                'permissions': (('view_province', 'Ver'), ('add_province', 'Añadir'), ('change_province', 'Editar'), ('delete_province', 'Eliminar')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=15, verbose_name='Nombre')),
                ('number', models.IntegerField(unique=True, verbose_name='Número')),
                ('latitude', models.FloatField(verbose_name='Latitud')),
                ('longitude', models.FloatField(verbose_name='Longitud')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations', to='meteo.province', verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'Estación',
                'verbose_name_plural': 'Estaciones',
                'ordering': ('name',),
                'permissions': (('view_station', 'Ver'), ('add_station', 'Añadir'), ('change_station', 'Editar'), ('delete_station', 'Eliminar')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=25, verbose_name='Nombre')),
                ('latitude', models.FloatField(verbose_name='Latitud')),
                ('longitude', models.FloatField(verbose_name='Longitud')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='towns', to='meteo.province', verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ('name',),
                'permissions': (('view_town', 'Ver'), ('add_town', 'Añadir'), ('change_town', 'Editar'), ('delete_town', 'Eliminar')),
                'default_permissions': (),
            },
        ),
    ]
