name: Dependabot auto-merge

on: pull_request

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    name: Auto-merge minor/patch
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          alert-lookup: true
          compat-lookup: true

      - name: Approve and merge non-major updates
        if: steps.metadata.outputs.update-type == 'version-update:semver-minor' || steps.metadata.outputs.update-type == 'version-update:semver-patch'
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr review "$PR_URL" --approve
          gh pr merge "$PR_URL" --squash --auto
